spring:
  application:
    name: TeamUP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.116.53.24:3306/team_up
    username: ryan
    password: ryanpsw
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: localhost
    database: 0

  profiles:
    active: dev
server:
  port: 8080
  servlet:
      context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: idDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)